### ISSUE TITLE
QYT-7900 issue

### ISSUE THREAD

**Issue by vladbondarenko** [mpoletiek/py3-CHIRP#20]
After Download i got an error:
```
(chirpwx.py:346071): Gtk-CRITICAL **: 18:54:18.772: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
Traceback (most recent call last):
  File "/home/fox/prog/py3-CHIRP/chirp/wxui/main.py", line 443, in _menu_download
    editorset = ChirpEditorSet(radio, None, self._editors)
  File "/home/fox/prog/py3-CHIRP/chirp/wxui/main.py", line 64, in __init__
    settings = settingsedit.ChirpCloneSettingsEdit(radio,
  File "/home/fox/prog/py3-CHIRP/chirp/wxui/settingsedit.py", line 94, in __init__
    self._settings = self._radio.get_settings()
  File "/home/fox/prog/py3-CHIRP/chirp/drivers/btech.py", line 1455, in get_settings
    LIST_RPTDL[_mem.settings.rptdl]))
IndexError: list index out of range
```

and as a result:
![image](https://user-images.githubusercontent.com/9531461/163682318-0b272902-ba72-4bbf-abf2-135532dc8b1c.png)

Python 3.8.10
Ubuntu 21.10
libgtk 3.24.30

Can this issue be fixed?

Thanks.

**Comment by mpoletiek** [comment]
Have you tried Ubuntu 20? Isn't that the LTS version?

Also, double check you have these dependencies:


    pyserial
    wxPython
    future
    six
    pyGObject (For the time being)
    libpython-dev (For Ubuntu users)

**Comment by mpoletiek** [comment]
Apologies, but this repo is not maintained.
